SPECIFICURLNAV/urls.py
from django.contrib import admin
from django.urls import path,include
import app1,app2
urlpatterns = [
    path('admin/', admin.site.urls),
    path('app1/',include('app1.urls')),
    path('app2/',include('app2.urls')),
]

app1/urls.py
from app1.views import *
from django.urls import path
app_name='something'
urlpatterns=[
    path('jyothi/',jyothi,name='jyothi'),
]

app2/urls.py
from app2.views import *
from django.urls import path
app_name='nothing'
urlpatterns=[
    path('kiran/',kiran,name='kiran')
]

app1/models.py
from django.db import models

# Create your models here.

app2/models.py
from django.db import models

# Create your models here.

app1/views.py
from django.shortcuts import render

# Create your views here.
def jyothi(request):
    return render(request,'jyothi.html')

app2/views.py
from django.shortcuts import render

# Create your views here.
def kiran(request):
    return render(request,'kiran.html')

templates/jyothi.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>Hello</h1>
        <h1>How are you ?</h1>
        <a href="{% url 'nothing:kiran' %}"><h1>Response of Kiran</h1> </a>
    </center>
</body>
</html>

templates/kiran.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>Hello </h1>
        <h1>I'm good</h1>
        <h1>How about you...</h1>
        <a href="{% url 'something:jyothi' %}"><h1>Response of jyothi</h1></a>
    </center>
</body>
</html>